FROM apache/airflow:2.3.1

RUN pip install --upgrade pip
RUN pip install --upgrade google-cloud-bigquery google-oauth mysql-connector mysql analytics-python workalendar pandas pandasql PyMySQL pymysql regex retry urllib3
RUN pip3 install --upgrade google-cloud-bigquery google-oauth mysql-connector mysql analytics-python workalendar pandas pandasql PyMySQL pymysql regex retry urllib3

